name: BlockDuels
version: '1.0-PREVIEW'
main: lukh.blockDuels.Main
api-version: '1.21'
authors: [ Luk_H ]
permissions:
  BlockDuels.battlemaster:
    description: "Commands to start and modify Duels"
    default: op
commands:
  addPlayer:
    description: "Add a player to the next duel"
    permission: BlockDuels.battlemaster
  removePlayer:
    description: "Remove a player from the next duel"
    permission: BlockDuels.battlemaster
  listPlayers:
    description: "Lists all Players enrolled in next duel or in current duel."
    permission: BlockDuels.battlemaster
  startDuel:
    description: "Starts the BlockDuel"
    permission: BlockDuels.battlemaster